kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: mautic
  name: mautic-db-pvc
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi